#' Plot predicted versus observed counts
#'
#' @param pred_df A data frame containing the predicted counts, as generated by
#' `predict_counts()`
#' @param data Data list (from `prepare_data()`)
#' @param byplant Logical. If TRUE, show predicted and observed counts per plant
#' (using `ggplot2::facet_wrap()`). If FALSE, show all interactions in the same plot.
#' @param .width probability cutoff to determine the width of the resulting interval (default 0.95).
#' @param .point point summary function, which takes a vector and returns a single value, e.g. [mean()], [median()], or [Mode()]
#' @param ... Further arguments to be passed to `ggplot2::facet_wrap()` if
#' `byplant = TRUE`, or to `tidybayes::geom_pointinterval()` if `byplant = FALSE`.
#'
#' @return A ggplot object
#' @export
#'
#' @examplesIf interactive()
#' data(web)
#' dt <- prepare_data(mat = web, plant_effort = rep(20, nrow(web)))
#' fit <- fit_model(dt, refresh = 0)
#' pred_df <- predict_counts(fit, dt)
#' plot_counts_pred_obs(pred_df, dt)
#' plot_counts_pred_obs(pred_df, dt, fatten_point = 3)
#' plot_counts_pred_obs(pred_df, dt, byplant = TRUE)
#' plot_counts_pred_obs(pred_df, dt, byplant = TRUE, scale = "free")

plot_counts_pred_obs <- function(pred_df = NULL, data = NULL, byplant = FALSE, .width = 0.95,
                                 .point = mean, ...) {

  obs <- data$M |>
    network.tools::wide2long(int.name = "Count.obs")

  pred <- pred_df |>
    dplyr::select(Plant, Animal, Count.pred = count) |>
    tidybayes::point_interval(.width = .width, .point = .point) |>
    dplyr::left_join(obs, by = c("Plant", "Animal"))

  gg <- ggplot2::ggplot(pred) +
    ggplot2::geom_abline(intercept = 0, slope = 1, lty = 2) +
    ggplot2::labs(x = "Observed counts", y = "Predicted counts")

  if (isTRUE(byplant)) {
    gg <- gg +
      tidybayes::geom_pointinterval(ggplot2::aes(x = Count.obs, y = Count.pred,
                                        ymin = .lower, ymax = .upper)) +
      ggplot2::facet_wrap(~Plant, ...)
  } else {
    gg <- gg +
      tidybayes::geom_pointinterval(ggplot2::aes(x = Count.obs, y = Count.pred,
                                        ymin = .lower, ymax = .upper),
                                    ...)
  }
  return(gg)
}
