#' Plot heatmap of predicted counts
#'
#' @param pred_df A data frame containing the predicted counts, as generated by
#' [predict_counts()]
#' @param .width probability cutoff to determine the width of the resulting interval (default 0.95)
#' @param .point point summary function, which takes a vector and returns a single value, e.g. [mean()], [median()], or [Mode()]
#' @param ... Further arguments for [network.tools::plot_web_heatmap()].
#'
#' @return A ggplot object
#' @export
#'
#' @examplesIf interactive()
#' data(web)
#' dt <- prepare_data(mat = web, plant_effort = rep(20, nrow(web)))
#' fit <- fit_model(dt, refresh = 0)
#' pred_df <- predict_counts(fit, dt)
#' plot_counts_pred(pred_df)
#' plot_counts_pred(pred_df, sort = FALSE)

plot_counts_pred <- function(pred_df = NULL, .width = 0.95, .point = mean, ...) {

  pred_df |>
    dplyr::select(Plant, Animal, count) |>
    tidybayes::point_interval(.width = .width, .point = .point) |>
    network.tools::plot_web_heatmap(int.var = "count", ...) +
    ggplot2::labs(title = "Predicted counts", fill = "")
}
